BROADCOM_GENXML_GENERATED_FILES = \
	cle/v3d_packet_v21_pack.h \
	cle/v3d_packet_v33_pack.h \
	$()

BROADCOM_GENXML_XML_FILES = \
	cle/v3d_packet_v21.xml \
	cle/v3d_packet_v33.xml \
	$()

BROADCOM_FILES = \
	cle/v3d_packet_helpers.h \
	cle/vc5_packet.h \
	$()

