/*
 * Copyright © 2016 Broadcom
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#ifndef VC5_PACKET_H
#define VC5_PACKET_H

enum vc5_packet {
        VC5_PACKET_HALT = 0,
        VC5_PACKET_NOP = 1,
        /* Adds return-from-sublist to tiles, and flushes tile lists. */
        VC5_PACKET_FLUSH = 4,
        /* Force all current state to be written to tiles, then FLUSH */
        VC5_PACKET_FLUSH_ALL = 5,

        VC5_PACKET_START_TILE_BINNING = 6,
        VC5_PACKET_INCREMENT_SEMAPHORE = 7,
        VC5_PACKET_WAIT_ON_SEMAPHORE = 8,
        VC5_PACKET_WAIT_PREV_FRAME = 9,
        VC5_PACKET_ENABLE_Z_ONLY = 10,
        VC5_PACKET_DISABLE_Z_ONLY = 11,
        VC5_PACKET_END_Z_ONLY = 12,
        VC5_PACKET_END_RENDER = 13,
        VC5_PACKET_CL_WAIT_TRANSFORM_FEEDBACK = 14,
        VC5_PACKET_BRANCH_SUB_AUTOCHAIN = 15,
        VC5_PACKET_BRANCH = 16,
        VC5_PACKET_BRANCH_SUB = 17,
        VC5_PACKET_RETURN = 18,
        VC5_PACKET_FLUSH_VCD_CACHE = 19,
        VC5_PACKET_GENERIC_TLIE_LIST = 20,
        VC5_PACKET_BRANCH_IMPLICIT_TILE = 21,
        VC5_PACKET_BRANCH_IMPLICIT_SUPERTILE = 22,
        VC5_PACKET_SUPERTILE_COORDS = 23,
        VC5_PACKET_STORE_SUBSAMPLE = 24,
        VC5_PACKET_STORE_SUBSAMPLE_EX = 25,
        VC5_PACKET_LOAD = 26,
        VC5_PACKET_END_TILE = 27,
        VC5_PACKET_STORE_GENERAL = 29,
        VC5_PACKET_LOAD_GENERAL = 30,
        VC5_PACKET_INDEXED_PRIM_LIST = 32,
        VC5_PACKET_INSTANCED_PRIM_LIST = 33,
        VC5_PACKET_INDEXED_INSTANCED_PRIM_LIST = 34,
        VC5_PACKET_INDEXED_SINGLE_INSTANCE_PRIM_LIST = 35,
        VC5_PACKET_VERTEX_ARRAY_PRIMS = 36,
        VC5_PACKET_INDIRECT_VERTEX_ARRAY_PRIMS = 37,
        VC5_PACKET_VERTEX_ARRAY_INSTANCED_PRIMS = 38,
        VC5_PACKET_VERTEX_ARRAY_SINGLE_INSTANCE_PRIMS = 39,
        VC5_PACKET_VG_COORD_ARRAY_PRIMS = 41,
        VC5_PACKET_VG_INLINE_PRIMS = 42,
        VC5_PACKET_BASE_VERTEX_BASE_INSTANCE = 43,
        VC5_PACKET_INDIRECT_PRIMITIVE_LIMITS = 44,
        VC5_PACKET_COMPRESSED_PRIM_LIST_IID_ZERO = 48,
        VC5_PACKET_COMPRESSED_PRIM_LIST_CURRENT_IID = 49,
        VC5_PACKET_GL_SHADER = 64,
        VC5_PACKET_GL_T_SHADER = 65,
        VC5_PACKET_GL_G_SHADER = 66,
        VC5_PACKET_GL_TG_SHADER = 67,
        VC5_PACKET_NV_SHADER = 68,
        VC5_PACKET_VG_SHADER = 69,
        VC5_PACKET_VG_INLINE_SHADER = 69,
        VC5_PACKET_VCM_CACHE_SIZE = 73,
        VC5_PACKET_TRANSFORM_FEEDBACK_ENABLE = 74,
        VC5_PACKET_FLUSH_TRANSFORM_FEEDBACK_DATA = 75,
        VC5_PACKET_L1_CACHE_FLUSH_CONTROL = 76,
        VC5_PACKET_L2T_CACHE_FLUSH_CONTROL = 77,
        VC5_PACKET_L2C_CACHE_FLUSH = 78,
        VC5_PACKET_STENCIL_CFG = 80,
        VC5_PACKET_BLEND_CFG = 84,
        VC5_PACKET_BLEND_COLOR = 86,
        VC5_PACKET_COLOR_WMASKS = 87,
        VC5_PACKET_ZERO_ALL_CENTROID_FLAGS = 88,
        VC5_PACKET_ZERO_ALL_FLATSHADE_FLAGS = 89,
        VC5_PACKET_SAMPLE_COVERAGE = 91,
        VC5_PACKET_OCCLUSION_QUERY_COUNTER_ENABLE = 92,
        VC5_PACKET_CFG_BITS = 96,
        VC5_PACKET_FLATSHADE_FLAGS = 98,
        VC5_PACKET_POINT_SIZE = 104,
        VC5_PACKET_LINE_WIDTH = 105,
        VC5_PACKET_DEPTH_OFFSET = 106,
        VC5_PACKET_CLIP = 107,
        VC5_PACKET_VIEWPORT_OFFSET = 108,
        VC5_PACKET_CLIP_Z = 109,
        VC5_PACKET_CLIPPER_XY = 110,
        VC5_PACKET_CLIPPER_Z = 111,
        VC5_PACKET_TILE_BINNING_MODE_CFG = 120,
        VC5_PACKET_TILE_RENDERING_MODE_CFG = 121,
        VC5_PACKET_MULTICORE_RENDERING_SUPERTILE_CFG = 122,
        VC5_PACKET_MULTICORE_RENDERING_TILE_LIST_BASE = 123,
        VC5_PACKET_TILE_COORDS = 124,
        VC5_PACKET_TILE_LIST_INITIAL_BLOCK_SIZE = 126,
};

#endif /* VC5_PACKET_H */
